### ISSUE TITLE
Which key is §?

### ISSUE THREAD

**Issue by jfromaniello** [mafredri/phoenix-config#1]
Awesome repository and code, does exactly what I wanted.

I am curious about this key mentioned in the readme ` §`. 

Thank you!

**Comment by mafredri** [comment]
Hi, I'm glad you like it!

The section sign (`§`) is located in the upper left corner of a Finnish keyboard layout.

![Finnish keyboard layout](http://ascii-table.com/img/keyboard-153.png)

It's pretty useless, which is why I've made it into a hotkey for the terminal. I think, on a US keyboard, the closest might be a "non us backslash".

If you want to re-map it, check what character your keyboard produces by pressing the key, and replace it with that.

Good luck!

**Comment by jfromaniello** [comment]
Thanks a lot! It is very interesting to learn this
