### ISSUE TITLE
Watch mode - update ~/.phoenix.js

### ISSUE THREAD

**Issue by boedy** [mafredri/phoenix-config#4]
Thanks for providing this repo. Gives me a great starting point to start tinkering.

I was just wondering. What was your workflow during development? I'm thinking I would like to use `yarn start` to automatically update `~/.phoenix.js` when I make changes. Did you manually copy over the output every time you made a change you wanted to test?

**Comment by mafredri** [comment]
Happy you found some use for it @boedy!

Perhaps a bit lazy, but my setup look like this:

```
❯ ls -l ~/.config/phoenix
lrwxr-xr-x  1 maf  staff    26B Jun 27  2022 /Users/maf/.config/phoenix@ -> ../Code/phoenix-config/out
```

Then I simply run `yarn watch` which watches the code for changes and updates  `phoenix-config/out/phoenix.js`, which is propagated to Phoenix due to the symlink.

If you want to mimic this, you can do so by quitting Phoenix:

```
rm ~/.phoenix.js
mkdir ~/.config
cd ~/.config
ln -s ../path/to/phoenix-config/out phoenix
```

And then start Phoenix. It's important to quit because Phoenix remembers the config file location as long as it's running, so it can't be moved.

**Comment by boedy** [comment]
Perfect. Thanks for explaining!

**Comment by ijpatricio** [comment]
@boedy Thank you!! Just diving in, and this is absolute bonkers!!!

Both Phoenix, and this setup within the repo!!!

I came to open issue, but someone already passed by the same :) Going to make a video and post about this!!

Thank you, thank you, thank you!!!

**Comment by ijpatricio** [comment]
@mafredri this previous post was to thank yooou!
